#----------------------------------------------------------------
HFILES =   AColorXYZV.H  ASpectralCurve.H  ASpectrum.H  ASunSky.H srgb.H

CFILES =   AAtmConstants.C  ASpectralCurve.C  ASunSky.C \
           AToSpectrum.C  srgb.C \
           AColorXYZV.C  ASunConstants.C   
OFILES =   AAtmConstants.o  ASpectralCurve.o   AColorXYZV.o    \
           ASunConstants.o  ASunSky.o   AToSpectrum.o   srgb.o

LIBF   =   libasky.a

default:   libasky.a

#----------------------------------------------------------------
include ../Makefile.setup
#----------------------------------------------------------------

include ./depend
